### ISSUE TITLE
Doesn't build with recent ghc-8.2

### ISSUE THREAD

**Issue by erikd** [phadej/cabal-doctest#12]
I've using GHC that I built from the ghc-8.2 branch (version is reported as 8.2.0.20170430) and cabal-doctest fails to build with:
```
src/Distribution/Extra/Doctest.hs:249:18: error:
    • Couldn't match type ‘Distribution.Types.MungedPackageId.MungedPackageId’
                     with ‘Distribution.Types.PackageId.PackageIdentifier’
      Expected type: [(UnitId, PackageId)]
        Actual type: [(UnitId,
                       Distribution.Types.MungedPackageId.MungedPackageId)]
    • In the expression:
        nub $ componentPackageDeps xs ++ componentPackageDeps ys
      In an equation for ‘testDeps’:
          testDeps xs ys
            = nub $ componentPackageDeps xs ++ componentPackageDeps ys
    |
249 | testDeps xs ys = nub $ componentPackageDeps xs ++ componentPackageDeps ys
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Thought you'd like to know.

**Comment by christiaanb** [comment]
This is enough to get it to build: https://github.com/christiaanb/cabal-doctest/commit/3e8e22abd53af14bb8f7ed402172ef30f31a3e9b

No idea if it does the right thing though... as it is only a transitive dependency of one of my projects, getting it to build was good enough for my purposes.

**Comment by phadej** [comment]
I actually "unbroke" rewriteFile, so have I'll procrastinate until that version of Cabal is in GHC tree

**Comment by phadej** [comment]
Fixed in 1.0.1
