### ISSUE TITLE
Build error with GHC-8.8.1

### ISSUE THREAD

**Issue by recursion-ninja** [phadej/cabal-doctest#51]
I get the following error when trying to build with 8.8.1:

```
Preprocessing library for cabal-doctest-1.0.6..
Building library for cabal-doctest-1.0.6..
[1 of 1] Compiling Distribution.Extra.Doctest
                     
/tmp/stack3057/cabal-doctest-1.0.6/src/Distribution/Extra/Doctest.hs:434:60: error:
    • Couldn't match type ‘Distribution.Types.LibraryName.LibraryName’
                     with ‘Maybe
                             Distribution.Types.UnqualComponentName.UnqualComponentName’
      Expected type: Library
                     -> Maybe Distribution.Types.UnqualComponentName.UnqualComponentName
        Actual type: Library
                     -> Distribution.Types.LibraryName.LibraryName
    • In the second argument of ‘(.)’, namely ‘libName’
      In the second argument of ‘(.)’, namely
        ‘fmap unUnqualComponentName . libName’
      In the expression: NameLib . fmap unUnqualComponentName . libName
    |                
434 |     mbLibraryName = NameLib . fmap unUnqualComponentName . libName
    |                                                            ^^^^^^^
  
```

I think the types exported from `cabal` might have changed with the new compiler.

**Comment by RyanGlScott** [comment]
Indeed, the version of `Cabal` that GHC bundles changed enough between GHC 8.8.1-alpha1 and -alpha2 that `cabal-doctest` doesn't compile with -alpha2. The general volatility of `Cabal`'s API in pre-release versions of GHC is why I don't want to make a new release of `cabal-doctest` until I know with certainty that the API has stabilized for the 8.8 release. Given that there hasn't even been a release candidate of 8.8.1 yet, I don't think we're at that point.

**Comment by RyanGlScott** [comment]
Until that point arrives, there is a patch in [`head.hackage`](https://github.com/hvr/head.hackage) for `cabal-doctest` that makes it work with -alpha2.
