### PR TITLE
Support GHC-8.8

### LINKED ISSUE #51: Build error with GHC-8.8.1
I get the following error when trying to build with 8.8.1:

```
Preprocessing library for cabal-doctest-1.0.6..
Building library for cabal-doctest-1.0.6..
[1 of 1] Compiling Distribution.Extra.Doctest
                     
/tmp/stack3057/cabal-doctest-1.0.6/src/Distribution/Extra/Doctest.hs:434:60: error:
    • Couldn't match type ‘Distribution.Types.LibraryName.LibraryName’
                     with ‘Maybe
                             Distribution.Types.UnqualComponentName.UnqualComponentName’
      Expected type: Library
                     -> Maybe Distribution.Types.UnqualComponentName.UnqualComponentName
        Actual type: Library
                     -> Distribution.Types.LibraryName.LibraryName
    • In the second argument of ‘(.)’, namely ‘libName’
      In the second argument of ‘(.)’, namely
        ‘fmap unUnqualComponentName . libName’
      In the expression: NameLib . fmap unUnqualComponentName . libName
    |                
434 |     mbLibraryName = NameLib . fmap unUnqualComponentName . libName
    |                                                            ^^^^^^^
  
```

I think the types exported from `cabal` might have changed with the new compiler.

### PR DESCRIPTION
**Pull request by phadej**
Fixes #51

### CODE REVIEW

**Comment by phadej** [comment]
This is no urgent to merge, before `ghc-paths` has a release. There are code changes, so one is tied to `head.hackage` if you want to use `doctest`.

File: .travis.yml [hunk 1]
```diff
@@ -1,10 +1,10 @@
 # This Travis job script has been generated by a script via
 #
-#   haskell-ci '--branches' 'master' '--jobs-selection=any' '--output' '.travis.yml' 'cabal.project'
+#   haskell-ci '--config' 'cabal.haskell-ci' 'cabal.project'
 #
 # For more information, see https://github.com/haskell-CI/haskell-ci
 #
-# version: 0.3.20190327
+# version: 0.3.20190730
```
Comment (RyanGlScott) [inline .travis.yml]: Wait, what version of `head.hackage` is this? :)

File: src/Distribution/Extra/Doctest.hs [hunk 2]
```diff
@@ -100,6 +100,16 @@ import Distribution.PackageDescription
        (CondTree (..))
 #endif
 
+#if MIN_VERSION_Cabal(3,0,0)
+import Distribution.Simple.Utils (findFileEx)
+#else
+import Distribution.Simple.Utils (findFile)
+#endif
+
+#if MIN_VERSION_Cabal(3,0,0)
```
Comment (RyanGlScott) [inline src/Distribution/Extra/Doctest.hs]: Perhaps combine this import with the earlier use of `MIN_VERSION_Cabal(3,0,0)` to minimize CPP?

File: .travis.yml (hunk 1 above)
Comment (phadej) [reply .travis.yml]: The one which doesn't treat 8.8 as needing head.hackage, yet it's made configurable in https://github.com/haskell-CI/haskell-ci/pull/289

File: src/Distribution/Extra/Doctest.hs (hunk 2 above)
Comment (phadej) [reply src/Distribution/Extra/Doctest.hs]: I feel uneasy here, I don't like merging CPP blocks which have multiple needs **and** `#else` branches.
i.e. it might look like I need `libraryNameString` for `findFile` functionality.

That said, I'm not consistent.

**Comment by RyanGlScott** [comment]
An 8.8-compatible `ghc-paths` release is now on Hackage, so I believe `doctest` is the only thing blocking this at present.

**Comment by phadej** [comment]
`allow-newer: doctest-0.16.1:ghc` would be fine for now.

**Comment by RyanGlScott** [comment]
Hah! `doctest-0.16.2` was released literally seconds after you posted https://github.com/phadej/cabal-doctest/pull/52#issuecomment-524837430 :)

File: cabal.haskell-ci [hunk 3]
```diff
@@ -0,0 +1,9 @@
+branches: master
+jobs-selection: any
+
+-- doctest needs ghc bounds relaxation
+--
+-- ghc-paths needs a release
+-- https://github.com/simonmar/ghc-paths/pull/19
+-- https://github.com/simonmar/ghc-paths/issues/18
+tests: <8.8
```
Comment (RyanGlScott) [inline cabal.haskell-ci]: This line can be removed now, right?

Comment (phadej) [reply cabal.haskell-ci]: good catch
